name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Java Merge Sirt
      id: java-merge-sirt
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Java Merge Sirt
        setup-command: ''
        command: gradle test
        timeout: 10
        max-score: 20
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        JAVA-MERGE-SIRT_RESULTS: "${{steps.java-merge-sirt.outputs.result}}"
      with:
        runners: java-merge-sirt
